### ISSUE TITLE
Error installing composer

### ISSUE THREAD

**Issue by zickkeen** [yii2mod/yii2-bootstrap-notify#1]
`#> composer require --prefer-dist yii2mod/yii2-bootstrap-notify "*"`
`Problem 1`
`   - yii2mod/yii2-bootstrap-notify 1.1 requires bower-asset/remarkable-bootstrap-notify * -> no matching package found.`
`   - yii2mod/yii2-bootstrap-notify 1.0 requires bower-asset/remarkable-bootstrap-notify * -> no matching package found.`
`   - Installation request for yii2mod/yii2-bootstrap-notify * -> satisfiable by yii2mod/yii2-bootstrap-notify[1.0, 1.1].`

`#> composer require --prefer-dist bower-asset/remarkable-bootstrap-notify "*"`
`  Problem 1`
`    - The requested package bower-asset/remarkable-bootstrap-notify could not be found in any version, there may be a typo in the package name.`

**Comment by ihorchepurnyi** [comment]
Hi, I use this package in my project without any errors. You need to install the composer asset plugin. Try this command:
```bash
composer global require "fxp/composer-asset-plugin:^1.2.0"
```

After this command done, try install this package again.
