### ISSUE TITLE
Multi notif error

### ISSUE THREAD

**Issue by zickkeen** [yii2mod/yii2-bootstrap-notify#2]
how to set multi notification error, i try like this:
`Yii::$app->session->setFlash('error', 'error message1');`
`Yii::$app->session->setFlash('error', 'error message2');`
but just showing "error message 2". and while I try change to warning to "error message2"
`Yii::$app->session->setFlash('error', 'error message1');`
`Yii::$app->session->setFlash('warning', 'error message2');`
its can show both.
so, how to set 2nd error message with same type??

**Comment by ihorchepurnyi** [comment]
Hi, please update your package. Now, you can set multiple messages as follows:
```php
Yii::$app->session->setFlash('error', ['Error 1', 'Error 2']);
```
